apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sds

resources:
  - namespace.yaml
  - provider-secret.yaml
  - configmap.yaml
  - pricing-config.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: harbor.mgmt.infra.graphops.xyz/infra/sds-provider
    newTag: latest
