apiVersion: v1
kind: Secret
metadata:
  name: sds-provider-secret
  labels:
    app.kubernetes.io/name: sds-provider
    app.kubernetes.io/component: provider-gateway
    app.kubernetes.io/part-of: substreams-data-service
type: Opaque
stringData:
  rpc-endpoint: "https://sepolia-rollup.arbitrum.io/rpc"
