// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/substreams/data_service/provider/v1/provider.proto

package providerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/provider/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProviderSidecarServiceName is the fully-qualified name of the ProviderSidecarService service.
	ProviderSidecarServiceName = "graph.substreams.data_service.provider.v1.ProviderSidecarService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProviderSidecarServiceValidatePaymentProcedure is the fully-qualified name of the
	// ProviderSidecarService's ValidatePayment RPC.
	ProviderSidecarServiceValidatePaymentProcedure = "/graph.substreams.data_service.provider.v1.ProviderSidecarService/ValidatePayment"
	// ProviderSidecarServiceReportUsageProcedure is the fully-qualified name of the
	// ProviderSidecarService's ReportUsage RPC.
	ProviderSidecarServiceReportUsageProcedure = "/graph.substreams.data_service.provider.v1.ProviderSidecarService/ReportUsage"
	// ProviderSidecarServiceEndSessionProcedure is the fully-qualified name of the
	// ProviderSidecarService's EndSession RPC.
	ProviderSidecarServiceEndSessionProcedure = "/graph.substreams.data_service.provider.v1.ProviderSidecarService/EndSession"
	// ProviderSidecarServiceGetSessionStatusProcedure is the fully-qualified name of the
	// ProviderSidecarService's GetSessionStatus RPC.
	ProviderSidecarServiceGetSessionStatusProcedure = "/graph.substreams.data_service.provider.v1.ProviderSidecarService/GetSessionStatus"
)

// ProviderSidecarServiceClient is a client for the
// graph.substreams.data_service.provider.v1.ProviderSidecarService service.
type ProviderSidecarServiceClient interface {
	// ValidatePayment validates a RAV received from a client.
	// Called by the provider when a client connects with a payment header.
	ValidatePayment(context.Context, *connect.Request[v1.ValidatePaymentRequest]) (*connect.Response[v1.ValidatePaymentResponse], error)
	// ReportUsage reports usage sent to a client.
	// Called by the provider as data is sent during streaming.
	ReportUsage(context.Context, *connect.Request[v1.ReportUsageRequest]) (*connect.Response[v1.ReportUsageResponse], error)
	// EndSession ends a session and reports final usage.
	// Called by the provider when a stream ends.
	EndSession(context.Context, *connect.Request[v1.EndSessionRequest]) (*connect.Response[v1.EndSessionResponse], error)
	// GetSessionStatus gets the current status of a payment session.
	GetSessionStatus(context.Context, *connect.Request[v1.GetSessionStatusRequest]) (*connect.Response[v1.GetSessionStatusResponse], error)
}

// NewProviderSidecarServiceClient constructs a client for the
// graph.substreams.data_service.provider.v1.ProviderSidecarService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProviderSidecarServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProviderSidecarServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	providerSidecarServiceMethods := v1.File_graph_substreams_data_service_provider_v1_provider_proto.Services().ByName("ProviderSidecarService").Methods()
	return &providerSidecarServiceClient{
		validatePayment: connect.NewClient[v1.ValidatePaymentRequest, v1.ValidatePaymentResponse](
			httpClient,
			baseURL+ProviderSidecarServiceValidatePaymentProcedure,
			connect.WithSchema(providerSidecarServiceMethods.ByName("ValidatePayment")),
			connect.WithClientOptions(opts...),
		),
		reportUsage: connect.NewClient[v1.ReportUsageRequest, v1.ReportUsageResponse](
			httpClient,
			baseURL+ProviderSidecarServiceReportUsageProcedure,
			connect.WithSchema(providerSidecarServiceMethods.ByName("ReportUsage")),
			connect.WithClientOptions(opts...),
		),
		endSession: connect.NewClient[v1.EndSessionRequest, v1.EndSessionResponse](
			httpClient,
			baseURL+ProviderSidecarServiceEndSessionProcedure,
			connect.WithSchema(providerSidecarServiceMethods.ByName("EndSession")),
			connect.WithClientOptions(opts...),
		),
		getSessionStatus: connect.NewClient[v1.GetSessionStatusRequest, v1.GetSessionStatusResponse](
			httpClient,
			baseURL+ProviderSidecarServiceGetSessionStatusProcedure,
			connect.WithSchema(providerSidecarServiceMethods.ByName("GetSessionStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// providerSidecarServiceClient implements ProviderSidecarServiceClient.
type providerSidecarServiceClient struct {
	validatePayment  *connect.Client[v1.ValidatePaymentRequest, v1.ValidatePaymentResponse]
	reportUsage      *connect.Client[v1.ReportUsageRequest, v1.ReportUsageResponse]
	endSession       *connect.Client[v1.EndSessionRequest, v1.EndSessionResponse]
	getSessionStatus *connect.Client[v1.GetSessionStatusRequest, v1.GetSessionStatusResponse]
}

// ValidatePayment calls
// graph.substreams.data_service.provider.v1.ProviderSidecarService.ValidatePayment.
func (c *providerSidecarServiceClient) ValidatePayment(ctx context.Context, req *connect.Request[v1.ValidatePaymentRequest]) (*connect.Response[v1.ValidatePaymentResponse], error) {
	return c.validatePayment.CallUnary(ctx, req)
}

// ReportUsage calls graph.substreams.data_service.provider.v1.ProviderSidecarService.ReportUsage.
func (c *providerSidecarServiceClient) ReportUsage(ctx context.Context, req *connect.Request[v1.ReportUsageRequest]) (*connect.Response[v1.ReportUsageResponse], error) {
	return c.reportUsage.CallUnary(ctx, req)
}

// EndSession calls graph.substreams.data_service.provider.v1.ProviderSidecarService.EndSession.
func (c *providerSidecarServiceClient) EndSession(ctx context.Context, req *connect.Request[v1.EndSessionRequest]) (*connect.Response[v1.EndSessionResponse], error) {
	return c.endSession.CallUnary(ctx, req)
}

// GetSessionStatus calls
// graph.substreams.data_service.provider.v1.ProviderSidecarService.GetSessionStatus.
func (c *providerSidecarServiceClient) GetSessionStatus(ctx context.Context, req *connect.Request[v1.GetSessionStatusRequest]) (*connect.Response[v1.GetSessionStatusResponse], error) {
	return c.getSessionStatus.CallUnary(ctx, req)
}

// ProviderSidecarServiceHandler is an implementation of the
// graph.substreams.data_service.provider.v1.ProviderSidecarService service.
type ProviderSidecarServiceHandler interface {
	// ValidatePayment validates a RAV received from a client.
	// Called by the provider when a client connects with a payment header.
	ValidatePayment(context.Context, *connect.Request[v1.ValidatePaymentRequest]) (*connect.Response[v1.ValidatePaymentResponse], error)
	// ReportUsage reports usage sent to a client.
	// Called by the provider as data is sent during streaming.
	ReportUsage(context.Context, *connect.Request[v1.ReportUsageRequest]) (*connect.Response[v1.ReportUsageResponse], error)
	// EndSession ends a session and reports final usage.
	// Called by the provider when a stream ends.
	EndSession(context.Context, *connect.Request[v1.EndSessionRequest]) (*connect.Response[v1.EndSessionResponse], error)
	// GetSessionStatus gets the current status of a payment session.
	GetSessionStatus(context.Context, *connect.Request[v1.GetSessionStatusRequest]) (*connect.Response[v1.GetSessionStatusResponse], error)
}

// NewProviderSidecarServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProviderSidecarServiceHandler(svc ProviderSidecarServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	providerSidecarServiceMethods := v1.File_graph_substreams_data_service_provider_v1_provider_proto.Services().ByName("ProviderSidecarService").Methods()
	providerSidecarServiceValidatePaymentHandler := connect.NewUnaryHandler(
		ProviderSidecarServiceValidatePaymentProcedure,
		svc.ValidatePayment,
		connect.WithSchema(providerSidecarServiceMethods.ByName("ValidatePayment")),
		connect.WithHandlerOptions(opts...),
	)
	providerSidecarServiceReportUsageHandler := connect.NewUnaryHandler(
		ProviderSidecarServiceReportUsageProcedure,
		svc.ReportUsage,
		connect.WithSchema(providerSidecarServiceMethods.ByName("ReportUsage")),
		connect.WithHandlerOptions(opts...),
	)
	providerSidecarServiceEndSessionHandler := connect.NewUnaryHandler(
		ProviderSidecarServiceEndSessionProcedure,
		svc.EndSession,
		connect.WithSchema(providerSidecarServiceMethods.ByName("EndSession")),
		connect.WithHandlerOptions(opts...),
	)
	providerSidecarServiceGetSessionStatusHandler := connect.NewUnaryHandler(
		ProviderSidecarServiceGetSessionStatusProcedure,
		svc.GetSessionStatus,
		connect.WithSchema(providerSidecarServiceMethods.ByName("GetSessionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.substreams.data_service.provider.v1.ProviderSidecarService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProviderSidecarServiceValidatePaymentProcedure:
			providerSidecarServiceValidatePaymentHandler.ServeHTTP(w, r)
		case ProviderSidecarServiceReportUsageProcedure:
			providerSidecarServiceReportUsageHandler.ServeHTTP(w, r)
		case ProviderSidecarServiceEndSessionProcedure:
			providerSidecarServiceEndSessionHandler.ServeHTTP(w, r)
		case ProviderSidecarServiceGetSessionStatusProcedure:
			providerSidecarServiceGetSessionStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProviderSidecarServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProviderSidecarServiceHandler struct{}

func (UnimplementedProviderSidecarServiceHandler) ValidatePayment(context.Context, *connect.Request[v1.ValidatePaymentRequest]) (*connect.Response[v1.ValidatePaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderSidecarService.ValidatePayment is not implemented"))
}

func (UnimplementedProviderSidecarServiceHandler) ReportUsage(context.Context, *connect.Request[v1.ReportUsageRequest]) (*connect.Response[v1.ReportUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderSidecarService.ReportUsage is not implemented"))
}

func (UnimplementedProviderSidecarServiceHandler) EndSession(context.Context, *connect.Request[v1.EndSessionRequest]) (*connect.Response[v1.EndSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderSidecarService.EndSession is not implemented"))
}

func (UnimplementedProviderSidecarServiceHandler) GetSessionStatus(context.Context, *connect.Request[v1.GetSessionStatusRequest]) (*connect.Response[v1.GetSessionStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.substreams.data_service.provider.v1.ProviderSidecarService.GetSessionStatus is not implemented"))
}
