// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/substreams/data_service/provider/v1/provider.proto

package providerv1

import (
	v1 "github.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatePaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed RAV from the client's payment header
	PaymentRav *v1.SignedRAV `protobuf:"bytes,1,opt,name=payment_rav,json=paymentRav,proto3" json:"payment_rav,omitempty"`
	// Client-provided session ID (if resuming)
	ClientSessionId string `protobuf:"bytes,2,opt,name=client_session_id,json=clientSessionId,proto3" json:"client_session_id,omitempty"`
	// Expected service parameters
	ServiceParams *v1.ServiceParameters `protobuf:"bytes,3,opt,name=service_params,json=serviceParams,proto3" json:"service_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentRequest) Reset() {
	*x = ValidatePaymentRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentRequest) ProtoMessage() {}

func (x *ValidatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentRequest.ProtoReflect.Descriptor instead.
func (*ValidatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatePaymentRequest) GetPaymentRav() *v1.SignedRAV {
	if x != nil {
		return x.PaymentRav
	}
	return nil
}

func (x *ValidatePaymentRequest) GetClientSessionId() string {
	if x != nil {
		return x.ClientSessionId
	}
	return ""
}

func (x *ValidatePaymentRequest) GetServiceParams() *v1.ServiceParameters {
	if x != nil {
		return x.ServiceParams
	}
	return nil
}

type ValidatePaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the payment is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// If not valid, the reason for rejection
	RejectionReason string `protobuf:"bytes,2,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// The session ID assigned by the provider sidecar
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Service parameters to return to the client
	ServiceParams *v1.ServiceParameters `protobuf:"bytes,4,opt,name=service_params,json=serviceParams,proto3" json:"service_params,omitempty"`
	// The escrow account associated with this payment
	EscrowAccount *v1.EscrowAccount `protobuf:"bytes,5,opt,name=escrow_account,json=escrowAccount,proto3" json:"escrow_account,omitempty"`
	// Available escrow balance in GRT (wei)
	AvailableBalance *v1.BigInt `protobuf:"bytes,6,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidatePaymentResponse) Reset() {
	*x = ValidatePaymentResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentResponse) ProtoMessage() {}

func (x *ValidatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentResponse.ProtoReflect.Descriptor instead.
func (*ValidatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatePaymentResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidatePaymentResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *ValidatePaymentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ValidatePaymentResponse) GetServiceParams() *v1.ServiceParameters {
	if x != nil {
		return x.ServiceParams
	}
	return nil
}

func (x *ValidatePaymentResponse) GetEscrowAccount() *v1.EscrowAccount {
	if x != nil {
		return x.EscrowAccount
	}
	return nil
}

func (x *ValidatePaymentResponse) GetAvailableBalance() *v1.BigInt {
	if x != nil {
		return x.AvailableBalance
	}
	return nil
}

type ReportUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The usage to report
	Usage         *v1.Usage `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageRequest) Reset() {
	*x = ReportUsageRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageRequest) ProtoMessage() {}

func (x *ReportUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageRequest.ProtoReflect.Descriptor instead.
func (*ReportUsageRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ReportUsageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportUsageRequest) GetUsage() *v1.Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ReportUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the session should continue
	ShouldContinue bool `protobuf:"varint,1,opt,name=should_continue,json=shouldContinue,proto3" json:"should_continue,omitempty"`
	// If should_continue is false, the reason for stopping
	StopReason string `protobuf:"bytes,2,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	// Whether a new RAV has been received
	RavUpdated    bool `protobuf:"varint,3,opt,name=rav_updated,json=ravUpdated,proto3" json:"rav_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageResponse) Reset() {
	*x = ReportUsageResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageResponse) ProtoMessage() {}

func (x *ReportUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportUsageResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ReportUsageResponse) GetShouldContinue() bool {
	if x != nil {
		return x.ShouldContinue
	}
	return false
}

func (x *ReportUsageResponse) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *ReportUsageResponse) GetRavUpdated() bool {
	if x != nil {
		return x.RavUpdated
	}
	return false
}

type EndSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Final usage for this session
	FinalUsage *v1.Usage `protobuf:"bytes,2,opt,name=final_usage,json=finalUsage,proto3" json:"final_usage,omitempty"`
	// Reason for ending the session
	Reason        v1.EndReason `protobuf:"varint,3,opt,name=reason,proto3,enum=graph.substreams.data_service.common.v1.EndReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetFinalUsage() *v1.Usage {
	if x != nil {
		return x.FinalUsage
	}
	return nil
}

func (x *EndSessionRequest) GetReason() v1.EndReason {
	if x != nil {
		return x.Reason
	}
	return v1.EndReason(0)
}

type EndSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The final RAV for this session
	FinalRav *v1.SignedRAV `protobuf:"bytes,1,opt,name=final_rav,json=finalRav,proto3" json:"final_rav,omitempty"`
	// Total usage for the session
	TotalUsage *v1.Usage `protobuf:"bytes,2,opt,name=total_usage,json=totalUsage,proto3" json:"total_usage,omitempty"`
	// Total value collected in GRT (wei)
	TotalValue    *v1.BigInt `protobuf:"bytes,3,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *EndSessionResponse) GetFinalRav() *v1.SignedRAV {
	if x != nil {
		return x.FinalRav
	}
	return nil
}

func (x *EndSessionResponse) GetTotalUsage() *v1.Usage {
	if x != nil {
		return x.TotalUsage
	}
	return nil
}

func (x *EndSessionResponse) GetTotalValue() *v1.BigInt {
	if x != nil {
		return x.TotalValue
	}
	return nil
}

type GetSessionStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session ID
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusRequest) Reset() {
	*x = GetSessionStatusRequest{}
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusRequest) ProtoMessage() {}

func (x *GetSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the session exists and is active
	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	// Current session information
	Session *v1.SessionInfo `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	// Current payment status
	PaymentStatus *v1.PaymentStatus `protobuf:"bytes,3,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusResponse) Reset() {
	*x = GetSessionStatusResponse{}
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusResponse) ProtoMessage() {}

func (x *GetSessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetSessionStatusResponse) GetSession() *v1.SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSessionStatusResponse) GetPaymentStatus() *v1.PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return nil
}

var File_graph_substreams_data_service_provider_v1_provider_proto protoreflect.FileDescriptor

const file_graph_substreams_data_service_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"8graph/substreams/data_service/provider/v1/provider.proto\x12)graph.substreams.data_service.provider.v1\x1a3graph/substreams/data_service/common/v1/types.proto\"\xfc\x01\n" +
	"\x16ValidatePaymentRequest\x12S\n" +
	"\vpayment_rav\x18\x01 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\n" +
	"paymentRav\x12*\n" +
	"\x11client_session_id\x18\x02 \x01(\tR\x0fclientSessionId\x12a\n" +
	"\x0eservice_params\x18\x03 \x01(\v2:.graph.substreams.data_service.common.v1.ServiceParametersR\rserviceParams\"\x99\x03\n" +
	"\x17ValidatePaymentResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12)\n" +
	"\x10rejection_reason\x18\x02 \x01(\tR\x0frejectionReason\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12a\n" +
	"\x0eservice_params\x18\x04 \x01(\v2:.graph.substreams.data_service.common.v1.ServiceParametersR\rserviceParams\x12]\n" +
	"\x0eescrow_account\x18\x05 \x01(\v26.graph.substreams.data_service.common.v1.EscrowAccountR\rescrowAccount\x12\\\n" +
	"\x11available_balance\x18\x06 \x01(\v2/.graph.substreams.data_service.common.v1.BigIntR\x10availableBalance\"y\n" +
	"\x12ReportUsageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12D\n" +
	"\x05usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\x05usage\"\x80\x01\n" +
	"\x13ReportUsageResponse\x12'\n" +
	"\x0fshould_continue\x18\x01 \x01(\bR\x0eshouldContinue\x12\x1f\n" +
	"\vstop_reason\x18\x02 \x01(\tR\n" +
	"stopReason\x12\x1f\n" +
	"\vrav_updated\x18\x03 \x01(\bR\n" +
	"ravUpdated\"\xcf\x01\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12O\n" +
	"\vfinal_usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\n" +
	"finalUsage\x12J\n" +
	"\x06reason\x18\x03 \x01(\x0e22.graph.substreams.data_service.common.v1.EndReasonR\x06reason\"\x88\x02\n" +
	"\x12EndSessionResponse\x12O\n" +
	"\tfinal_rav\x18\x01 \x01(\v22.graph.substreams.data_service.common.v1.SignedRAVR\bfinalRav\x12O\n" +
	"\vtotal_usage\x18\x02 \x01(\v2..graph.substreams.data_service.common.v1.UsageR\n" +
	"totalUsage\x12P\n" +
	"\vtotal_value\x18\x03 \x01(\v2/.graph.substreams.data_service.common.v1.BigIntR\n" +
	"totalValue\"8\n" +
	"\x17GetSessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xe1\x01\n" +
	"\x18GetSessionStatusResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12N\n" +
	"\asession\x18\x02 \x01(\v24.graph.substreams.data_service.common.v1.SessionInfoR\asession\x12]\n" +
	"\x0epayment_status\x18\x03 \x01(\v26.graph.substreams.data_service.common.v1.PaymentStatusR\rpaymentStatus2\xec\x04\n" +
	"\x16ProviderSidecarService\x12\x98\x01\n" +
	"\x0fValidatePayment\x12A.graph.substreams.data_service.provider.v1.ValidatePaymentRequest\x1aB.graph.substreams.data_service.provider.v1.ValidatePaymentResponse\x12\x8c\x01\n" +
	"\vReportUsage\x12=.graph.substreams.data_service.provider.v1.ReportUsageRequest\x1a>.graph.substreams.data_service.provider.v1.ReportUsageResponse\x12\x89\x01\n" +
	"\n" +
	"EndSession\x12<.graph.substreams.data_service.provider.v1.EndSessionRequest\x1a=.graph.substreams.data_service.provider.v1.EndSessionResponse\x12\x9b\x01\n" +
	"\x10GetSessionStatus\x12B.graph.substreams.data_service.provider.v1.GetSessionStatusRequest\x1aC.graph.substreams.data_service.provider.v1.GetSessionStatusResponseB\xed\x02\n" +
	"-com.graph.substreams.data_service.provider.v1B\rProviderProtoP\x01Zhgithub.com/graphprotocol/substreams-data-service/pb/graph/substreams/data_service/provider/v1;providerv1\xa2\x02\x04GSDP\xaa\x02(Graph.Substreams.DataService.Provider.V1\xca\x02(Graph\\Substreams\\DataService\\Provider\\V1\xe2\x024Graph\\Substreams\\DataService\\Provider\\V1\\GPBMetadata\xea\x02,Graph::Substreams::DataService::Provider::V1b\x06proto3"

var (
	file_graph_substreams_data_service_provider_v1_provider_proto_rawDescOnce sync.Once
	file_graph_substreams_data_service_provider_v1_provider_proto_rawDescData []byte
)

func file_graph_substreams_data_service_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_graph_substreams_data_service_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_graph_substreams_data_service_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_provider_v1_provider_proto_rawDesc), len(file_graph_substreams_data_service_provider_v1_provider_proto_rawDesc)))
	})
	return file_graph_substreams_data_service_provider_v1_provider_proto_rawDescData
}

var file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_graph_substreams_data_service_provider_v1_provider_proto_goTypes = []any{
	(*ValidatePaymentRequest)(nil),   // 0: graph.substreams.data_service.provider.v1.ValidatePaymentRequest
	(*ValidatePaymentResponse)(nil),  // 1: graph.substreams.data_service.provider.v1.ValidatePaymentResponse
	(*ReportUsageRequest)(nil),       // 2: graph.substreams.data_service.provider.v1.ReportUsageRequest
	(*ReportUsageResponse)(nil),      // 3: graph.substreams.data_service.provider.v1.ReportUsageResponse
	(*EndSessionRequest)(nil),        // 4: graph.substreams.data_service.provider.v1.EndSessionRequest
	(*EndSessionResponse)(nil),       // 5: graph.substreams.data_service.provider.v1.EndSessionResponse
	(*GetSessionStatusRequest)(nil),  // 6: graph.substreams.data_service.provider.v1.GetSessionStatusRequest
	(*GetSessionStatusResponse)(nil), // 7: graph.substreams.data_service.provider.v1.GetSessionStatusResponse
	(*v1.SignedRAV)(nil),             // 8: graph.substreams.data_service.common.v1.SignedRAV
	(*v1.ServiceParameters)(nil),     // 9: graph.substreams.data_service.common.v1.ServiceParameters
	(*v1.EscrowAccount)(nil),         // 10: graph.substreams.data_service.common.v1.EscrowAccount
	(*v1.BigInt)(nil),                // 11: graph.substreams.data_service.common.v1.BigInt
	(*v1.Usage)(nil),                 // 12: graph.substreams.data_service.common.v1.Usage
	(v1.EndReason)(0),                // 13: graph.substreams.data_service.common.v1.EndReason
	(*v1.SessionInfo)(nil),           // 14: graph.substreams.data_service.common.v1.SessionInfo
	(*v1.PaymentStatus)(nil),         // 15: graph.substreams.data_service.common.v1.PaymentStatus
}
var file_graph_substreams_data_service_provider_v1_provider_proto_depIdxs = []int32{
	8,  // 0: graph.substreams.data_service.provider.v1.ValidatePaymentRequest.payment_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	9,  // 1: graph.substreams.data_service.provider.v1.ValidatePaymentRequest.service_params:type_name -> graph.substreams.data_service.common.v1.ServiceParameters
	9,  // 2: graph.substreams.data_service.provider.v1.ValidatePaymentResponse.service_params:type_name -> graph.substreams.data_service.common.v1.ServiceParameters
	10, // 3: graph.substreams.data_service.provider.v1.ValidatePaymentResponse.escrow_account:type_name -> graph.substreams.data_service.common.v1.EscrowAccount
	11, // 4: graph.substreams.data_service.provider.v1.ValidatePaymentResponse.available_balance:type_name -> graph.substreams.data_service.common.v1.BigInt
	12, // 5: graph.substreams.data_service.provider.v1.ReportUsageRequest.usage:type_name -> graph.substreams.data_service.common.v1.Usage
	12, // 6: graph.substreams.data_service.provider.v1.EndSessionRequest.final_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	13, // 7: graph.substreams.data_service.provider.v1.EndSessionRequest.reason:type_name -> graph.substreams.data_service.common.v1.EndReason
	8,  // 8: graph.substreams.data_service.provider.v1.EndSessionResponse.final_rav:type_name -> graph.substreams.data_service.common.v1.SignedRAV
	12, // 9: graph.substreams.data_service.provider.v1.EndSessionResponse.total_usage:type_name -> graph.substreams.data_service.common.v1.Usage
	11, // 10: graph.substreams.data_service.provider.v1.EndSessionResponse.total_value:type_name -> graph.substreams.data_service.common.v1.BigInt
	14, // 11: graph.substreams.data_service.provider.v1.GetSessionStatusResponse.session:type_name -> graph.substreams.data_service.common.v1.SessionInfo
	15, // 12: graph.substreams.data_service.provider.v1.GetSessionStatusResponse.payment_status:type_name -> graph.substreams.data_service.common.v1.PaymentStatus
	0,  // 13: graph.substreams.data_service.provider.v1.ProviderSidecarService.ValidatePayment:input_type -> graph.substreams.data_service.provider.v1.ValidatePaymentRequest
	2,  // 14: graph.substreams.data_service.provider.v1.ProviderSidecarService.ReportUsage:input_type -> graph.substreams.data_service.provider.v1.ReportUsageRequest
	4,  // 15: graph.substreams.data_service.provider.v1.ProviderSidecarService.EndSession:input_type -> graph.substreams.data_service.provider.v1.EndSessionRequest
	6,  // 16: graph.substreams.data_service.provider.v1.ProviderSidecarService.GetSessionStatus:input_type -> graph.substreams.data_service.provider.v1.GetSessionStatusRequest
	1,  // 17: graph.substreams.data_service.provider.v1.ProviderSidecarService.ValidatePayment:output_type -> graph.substreams.data_service.provider.v1.ValidatePaymentResponse
	3,  // 18: graph.substreams.data_service.provider.v1.ProviderSidecarService.ReportUsage:output_type -> graph.substreams.data_service.provider.v1.ReportUsageResponse
	5,  // 19: graph.substreams.data_service.provider.v1.ProviderSidecarService.EndSession:output_type -> graph.substreams.data_service.provider.v1.EndSessionResponse
	7,  // 20: graph.substreams.data_service.provider.v1.ProviderSidecarService.GetSessionStatus:output_type -> graph.substreams.data_service.provider.v1.GetSessionStatusResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_graph_substreams_data_service_provider_v1_provider_proto_init() }
func file_graph_substreams_data_service_provider_v1_provider_proto_init() {
	if File_graph_substreams_data_service_provider_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_substreams_data_service_provider_v1_provider_proto_rawDesc), len(file_graph_substreams_data_service_provider_v1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_substreams_data_service_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_graph_substreams_data_service_provider_v1_provider_proto_depIdxs,
		MessageInfos:      file_graph_substreams_data_service_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_graph_substreams_data_service_provider_v1_provider_proto = out.File
	file_graph_substreams_data_service_provider_v1_provider_proto_goTypes = nil
	file_graph_substreams_data_service_provider_v1_provider_proto_depIdxs = nil
}
